FillmeUp/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
#from posts import views

urlpatterns = [
    # Examples:

    url(r'^$', 'posts.views.home', name='home'),
    url(r'^about_us/', 'posts.views.about_us',name='about_us'),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^posts/',include("posts.urls",namespace='posts')),
    url(r'^volunteer/', include('volunteer.urls', namespace="volunteer")),
    url(r'^donate/', include('donate.urls', namespace="donate")),

    url(r'^accounts/', include('allauth.urls')),
    url(r'^account/', include('accounts.urls', namespace="accounts")),
    url(r'^user/', include('users.urls', namespace="user")),


    #url(r'^posts/$', "<appname>.views.<function_name>"),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from .views import(
    post_list,
    post_create,
    post_delete,
    post_update,
    post_detail,
    )
#from posts import views

urlpatterns = [
    # Examples:
    #url(r'^$', '.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),


    #url(r'^$', "posts.views.post_home"),




    url(r'^$', post_list, name='list'),
    url(r'^create/$', post_create, name='create'),
    url(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', post_update, name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', post_delete),
    #url(r'^posts/$', "<appname>.views.<function_name>"),


]

users/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
	url(r'^list/', ListView.as_view(), name="list_user"),
	url(r'^(?P<slug>[\w-]+)/$', ProfileView.as_view(), name="show_profile"),
	url(r'^(?P<slug>[\w-]+)/update/$', UpdateView.as_view(), name="update_profile"),
	url(r'^(?P<slug>[\w-]+)/delete/$', DeleteView.as_view(), name="delete_profile"),
	url(r'^(?P<slug>[\w-]+)/block/$', BlockView.as_view(), name="block_profile"),
]

volunteer/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [
	url(r'^list/$', ListView.as_view(), name="list_volunteer"),
	url(r'^add/$', CreateView.as_view(), name="add_volunteer"),
	url(r'^(?P<slug>[\w-]+)/$', DetailView.as_view(), name="show_volunteer"),
	url(r'^(?P<slug>[\w-]+)/update/$', UpdateView.as_view(), name="update_volunteer"),
	url(r'^(?P<slug>[\w-]+)/delete/$', DeleteView.as_view(), name="delete_volunteer"),
	url(r'^(?P<slug>[\w-]+)/block/$', BlockView.as_view(), name="block_volunteer"),
	url(r'^(?P<slug>[\w-]+)/report/$', ReportView.as_view(), name="report_volunteer"),
]

volunteer/models.py
from django.db import models
from django.db.models.signals import pre_save, post_save

from django.core.urlresolvers import reverse
from django.utils.text import slugify




# Create your models here.


def upload_location(instance, filename):
    return "%s/%s/%s" % ("volunteer", instance.name, filename)

VERIFICATION_CHOICE = (
    (0, "Pending"),
    (1, "Verified"),
)


class Volunteer(models.Model):
    name = models.CharField(max_length=100, unique=True)
    address = models.CharField(max_length=100)
    contact_no = models.CharField(max_length=15, unique=True)
    website = models.URLField(max_length=100, unique=True)
    email = models.EmailField(max_length=100, unique=True)
    content = models.TextField()
    event_date = models.DateField(null=True)
    verification_status = models.IntegerField(
        default=0, choices=VERIFICATION_CHOICE)
    image = models.ImageField(upload_to=upload_location, null=True,
                              height_field="height_field", width_field="width_field")
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    average_rating = models.IntegerField(default=0)
    blocked = models.BooleanField(default=False)
    slug = models.SlugField(unique=True)

    class Meta:
        ordering = ["-name", ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("volunteer:show_volunteer", kwargs={"slug": self.slug})


def create_slug(sender, instance, *args, **kwargs):
    slug = slugify(instance.name)
    instance.slug = slug

pre_save.connect(create_slug, sender=Volunteer)

RATING_CHOICE = (
    (1, "1"),
    (2, "2"),
    (3, "3"),
    (4, "4"),
    (5, "5"),
)


class Review(models.Model):
    #user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    volunteer = models.ForeignKey(Volunteer, on_delete=models.CASCADE)
    rating = models.IntegerField(choices=RATING_CHOICE)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)

    def __str__(self):
        return self.content


class Report(models.Model):
    #user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    volunteer = models.ForeignKey(Volunteer, on_delete=models.CASCADE)
    title = models.CharField(max_length=20)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    verification_status = models.IntegerField(
        default=0, choices=VERIFICATION_CHOICE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("report_detail", kwargs={"id": self.id})

volunteer/forms.py
from django import forms

from .models import Volunteer, Review, Report

class VolunteerForm(forms.ModelForm):
	VERIFICATION_CHOICE = (
		(0,"Pending"),
		(1,"Verified"),
	)
	class Meta:
		model = Volunteer
		fields = [
			"name",
			"address",
			"contact_no",
			"website",
			"email",
			"image",
			"content",
			"event_date",
			# "verification_status",
		]
		widgets={
			"name":forms.TextInput(attrs={
				'required': 'true',
                'placeholder': 'Name',
                'class': 'form-control',
				}
			),
			"address":forms.TextInput(attrs={
				'required': 'true',
                'placeholder': 'Address',
                'class': 'form-control',
				}
			),
			"contact_no":forms.TextInput(attrs={
				'required': 'true',
                'placeholder': 'Contact No',
                'class': 'form-control',
				}
			),
			"website":forms.TextInput(attrs={
                'placeholder': 'hppts://www.example.com',
                'class': 'form-control',
				}
			),
			"email":forms.TextInput(attrs={
				'required': 'true',
                'placeholder': 'example@example.com',
                'class': 'form-control',
				}
			),
			"event_date":forms.DateInput(attrs={
				'required':'true',
				'placeholder':'Eventdate',
				'class': 'form-control',
				}
			),
			"registration_no":forms.TextInput(attrs={
				'required': 'true',
                'placeholder': 'Regitration No',
                'class': 'form-control',
				}
			),
			"image":forms.ClearableFileInput(attrs={
				'required': 'true',
				}
			)
		}


class ReviewForm(forms.ModelForm):
	class Meta:
		model = Review
		fields = [
			"rating",
			"content",
		]
		widgets={
			"rating":forms.Select(attrs={
				'required':'true',
				'class':'form-control'

				}
			),
			"content":forms.Textarea(attrs={
				'required':'true',
				'placeholder':'Review',
				'class':'col-md-10 form-control',
				'rows':'8',
				}
			),
		}

class ReportForm(forms.ModelForm):
	class Meta:
		model = Report
		fields = [
			"title",
			"content",
		]
		widgets={
			"title":forms.TextInput(attrs={
				'required':'true',
				'placeholder':'Title',
				'class':'form-control',
				}
			),
			"content":forms.Textarea(attrs={
				'required': 'true',
                'placeholder': 'Report',
                'class':'col-md-10 form-control',
				'rows':'8',
				}
			),
		}

volunteer/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect
from django.views.generic import View
from django.contrib import messages
from django.db.models import Q

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

#from user.models import UserProfile
from .models import Volunteer, Review, Report
from .forms import VolunteerForm, ReviewForm, ReportForm

# Create your views here.


class CreateView(View):

    def get(self, request):
        form = VolunteerForm(request.POST or None, request.FILES or None)

        context = {
            "form": form,
            "title": "Create Volunteer"
        }

        return render(request, "volunteer/create.html", context)

    def post(self, request):
        form = VolunteerForm(request.POST or None, request.FILES or None)

        if form.is_valid():
            volunteer = form.save(commit=False)

            if request.user.is_superuser or request.user.is_staff:
                volunteer.verification_status = 1
            else:
                volunteer.verification_status = 0

            volunteer.save()

            return HttpResponseRedirect(volunteer.get_absolute_url())
        else:
            print (form.errors)

        context = {
            "form": form,
            "title": "Create Volunteer"
        }

        return render(request, "volunteer/create.html", context)


class UpdateView(View):

    def get(self, request, slug=None):
        instance = get_object_or_404(Volunteer, slug=slug)
        form = VolunteerForm(request.POST or None,
                            request.FILES or None, instance=instance)

        context = {
            "form": form,
            "title": "Update Volunteer Details"
        }

        return render(request, "volunteer/update.html", context)

    def post(self, request, slug=None):
        instance = get_object_or_404(Volunteer, slug=slug)
        form = VolunteerForm(request.POST or None,
                            request.FILES or None, instance=instance)

        if form.is_valid():
            volunteer = form.save(commit=False)
            if request.user.is_superuser or request.user.is_staff:
                volunteer.verification_status = 1
            else:
                volunteer.verification_status = 0

            volunteer.save()

            return HttpResponseRedirect(volunteer.get_absolute_url())

        context = {
            "form": form,
            "title": "Update Volunteer Details"
        }

        return render(request, "volunteer/update.html", context)


class DetailView(View):

    def get(self, request, slug):
        volunteer = get_object_or_404(Volunteer, slug=slug)
        form = ReviewForm(request.POST or None)

        reviews = Review.objects.filter(volunteer=volunteer)

        context = {
            "volunteer": volunteer,
            "reviews": reviews,
            "form": form,
            "title": "Volunteer Details"
        }

        return render(request, "volunteer/detail.html", context)

    def post(self, request, slug):
        volunteer = get_object_or_404(Volunteer, slug=slug)
        user = get_object_or_404(UserProfile, user=request.user)
        print(user)
        form = ReviewForm(request.POST or None)

        if form.is_valid():
            review = form.save(commit=False)
            review.user = user
            review.volunteer = volunteer
            review.save()
            return HttpResponseRedirect(volunteer.get_absolute_url())

        context = {
            "volunteer": volunteer,
            "form": form,
            "title": "volunteer Details"
        }

        return render(request, "volunteer/detail.html", context)


class ListView(View):

    def get(self, request):
        object_list = Volunteer.objects.all().order_by("name")
        query = request.GET.get("query")
        if query:
            object_list = object_list.filter(
                Q(name__icontains=query) |
                Q(address__icontains=query) |
                Q(website__icontains=query) |
                Q(registration_no__icontains=query) |
                Q(email__icontains=query)
            ).distinct()

        paginator = Paginator(object_list, 2)  # Show 25 contacts per page
        page_request_var = "page"
        page = request.GET.get(page_request_var)
        try:
            object = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            object = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of
            # results.
            object = paginator.page(paginator.num_pages)

        context = {
            "object_list": object,
            "page_request_var": page_request_var,
            "title": "List of Volunteers"
        }

        return render(request, "volunteer/list.html", context)


class DeleteView(View):

    def get(self, request, slug):
        instance = get_object_or_404(Volunteer, slug=slug)
        instance.delete()

        return redirect('home')


class BlockView(View):

    def get(self, request, slug):
        instance = get_object_or_404(Volunteer, slug=slug)
        instance.blocked = True
        instance.save()

        return redirect('home')


class ReportView(View):
    def get(self, request, slug):
        volunteer = get_object_or_404(Volunteer, slug=slug)
        user = get_object_or_404(UserProfile, user=request.user)
        form = ReportForm(request.POST or None)

        context = {
            "volunteer": volunteer,
            "user": user,
            "form": form,
            "title": "Report a Volunteer"
        }

        return render(request, "volunteer/report.html", context)

    def post(self, request, slug):
        volunteer = get_object_or_404(Volunteer, slug=slug)
        user = get_object_or_404(UserProfile, user=request.user)
        form = ReportForm(request.POST or None)

        if form.is_valid():
            report = form.save(commit=False)
            report.user = user
            report.volunteer = volunteer
            report.save()
            return HttpResponseRedirect(volunteer.get_absolute_url())

        context = {
            "volunteer": volunteer,
            "user": user,
            "form": form,
            "title": "Report a Volunteer"
        }

        return render(request, "volunteer/report.html", context)


class ReportDetailView(View):
    def get(self, request, id=None):
        report = get_object_or_404(Report, id=id)

        context = {
            "report": report,
            "title": "Report Detail"
        }

        return render(request, "volunteer/report_detail.html", context)


class ReportListView(View):
    def get(self, request):
        object_list = Report.objects.all()  # .order_by("-timestamp")

        paginator = Paginator(object_list, 1)  # Show 25 contacts per page
        page_request_var = "page"
        page = request.GET.get(page_request_var)
        try:
            object = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            object = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of
            # results.
            object = paginator.page(paginator.num_pages)

        context = {
            "object_list": object,
            "page_request_var": page_request_var,
            "title": "List of Reports"
        }

        return render(request, "volunteer/report_list.html", context)


class ReportDeleteView(View):

    def get(self, request, id):
        instance = get_object_or_404(Report, id=id)
        instance.delete()
        return redirect('home')


class ReportVerifyView(View):

    def get(self, request, id):
        instance = get_object_or_404(Report, id=id)
        instance.verification_status = 1
        instance.save()
        return redirect('home')

templates/volunteer/create.html
{% extends "base.html" %}
{%load static%}

{% block title_head %}
	Volunteering Events | Add
{% endblock  %}


{% block content %}
<section class="contact-section">
<div class="container">
    <div class="portlet light">
        <div class="portlet-title">
            <div class="caption"><hr>
                <i class="fa fa-plus font-green-sharp"></i>
                <span class="caption-subject font-green-sharp bold uppercase">Add a Event<hr/></span>
            </div>
        </div>
        <div class="portlet-body form">
            <form id="contact-form" role="form" method="POST" action="" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-body">
                	<div class="form-group">
                        <label id="name" for="{{form.name.id_for_label}}" >Name</label>
                        <div class="input-group">

                            {{form.name}}
                        </div>
                    </div>
                    <div class="form-group">
                        <label id="address" for="{{form.address.id_for_label}}" >Address</label>
                        <div class="input-group">

                            {{form.address}}
                        </div>
                    </div>
                    <div class="form-group">
                        <label id="contact_no" for="{{form.contact_no.id_for_label}}" >Contact No</label>
                        <div class="input-group">

                            {{form.contact_no}}
                        </div>
                    </div>
                    <div class="form-group">
    					<label id="website" for="{{form.website.id_for_label}}" >Website</label>
                        <div class="input-group">

                            {{form.website}}
                        </div>
                    </div>
                    <div class="form-group">
    					<label id="email" for="{{form.email.id_for_label}}" >Email</label>
                        <div class="input-group">

                            {{form.email}}
                        </div>
                    </div>

                        </div>
                    </div>
                    <div class="form-group">
                        <label id="image" for="{{form.image.id_for_label}}" >Image</label>
                        <div class="input-group">
    						{{form.image}}
                <hr>
                <div class="form-group">
                    <label id="content" for="{{form.content.id_for_label}}" >Description</label>
                    <div class="input-group">

                    {{form.content}}
                        </div>
                    </div>
                    <button class="margin-top-20 btn blue" type="submit">Add Event</button>
                </div>
            </form>
            
        </div>
      </div>

</section>
{% endblock content %}

templates/volunteer/detail.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
	Volunteer | {{volunteer.name}}
{% endblock  %}


{% block content %}
<section class="blog-section">
	<div class="page-content">
		<div class="container">
			<div class="portlet light">
				<div class="portlet-body">
					<div class="blog-page">
						<div class="row">
							<div class="col-md-3 article-block">
							<div class="blog-tag-data">
								<img src="{{volunteer.image.url}}" class="img-responsive" alt="">
							</div>
							</div>
							<div class="col-md-9 blog-sidebar">
								<div class="portlet light">
									<div class="portlet-title">
										<div class="caption">
											<span style="font-size:40px;" class="caption-subject">{{volunteer.name}}</span>
											{% if not volunteer.blocked %}
												{% if volunteer.verification_status %}
												<span class="label label-success">Verified</span>
												{% else %}
												<span class="label label-warning">Pending</span>
												{% endif %}
											{% else %}
												<span class="label label-danger">Blocked</span>
											{% endif %}

										</div>
										<div class="actions">
											<a href="#" class="btn btn-circle btn-default">
											<i class="fa fa-edit"></i> Take part </a>
											<a href="#" class="btn btn-circle btn-default">
											<i class="fa fa-edit"></i> Interested </a>
										</div>
									</div>
									<div class="portlet-body">
										<h4>{{volunteer.average_rating}} <small><span class="fa fa-star"></span></small></h4>
										<h4><small><span class="fa fa-map-marker"></span></small>  {{volunteer.address}}</h4>
										<h4><small><span class="fa fa-globe"></span></small>  <a href="{{volunteer.website}}">{{volunteer.website}}</a> </h4>
										<h4><small><span class="fa fa-envelope"></span></small>  {{volunteer.email}}</h4>
										<h4><small><span class="fa fa-phone"></span></small>  {{volunteer.contact_no}}</h4>
                    <h4><small><span class="fa fa-table"></span></small>  {{volunteer.content}}</h4>
									</div>
								</div>
							</div>
						<!--end col-md-3-->
						</div>
						<hr/>
						<div class="row">
							<div class="col-md-9">
								<div class="media">
									<h3>Reviews</h3>
									{% for review in Reviews %}
									<a href="javascript:;" class="pull-left">
										<img alt="" src="{% static 'madara.jpg' %}" class="media-object">
									</a>
									<div class="media-body">
										<h4 class="media-heading"><a href="{% url 'user:show_profile' review.user.user|slugify%}">{{review.user.user}}</a>

											<span>
												{{review.timestamp|timesince}} ago
											</span>
										</h4>
										{{review.rating}}
										<p>
										{{review.content}}
										</p>
										<hr>
									</div>
									{% endfor %}
								</div>

								<hr>
								<div class="post-comment">
									<h3>Review</h3>
									<form role="form" action="" method="POST">
										{% csrf_token %}
										<div class="form-group">
											<h4><span class="fa fa-star-o"></span><span class="fa fa-star-o"></span><span class="fa fa-star-o"></span><span class="fa fa-star-o"></span><span class="fa fa-star-o"></span></h4>
											{{form.rating}}
											{{form.content}}
										</div>
										<button class="margin-top-20 btn blue" type="submit">Post a Review</button>
									</form>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock content %}

templates/volunteer/list.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}
	Events | Lists
{% endblock  %}


{% block content %}
<section class="page-banner-section">
	<div class="container">
		<h1>Upcoming Events</h1>
	</div>
</section>
<section class="blog-section">
	<div class="container">
		<div class="row">
			<div class="col-md-8">
				<div class="blog-box">
					<div class="blog-post">
			{% for object in object_list%}
				<div class="row">
					<div class="col-md-10 col-md-offset-1">
						<div class="tabbable tabbable-custom tabbable-noborder">
							<div class="tab-content">
								<div id="tab_2_2" class="tab-pane active">
									<div class="row booking-results">
										<div class="col-md-12">
											<div class="booking-result">
												<div class="booking-img">
													<img src="{{object.image.url}}" alt="">
													<ul class="list-unstyled price-location">
														<li>
															<i class="fa fa-map-marker"></i> {{object.address}}
														</li>
														<li>
															<i class="fa fa-envelope"></i> {{object.email}}
														</li>
														<li>
															<i class="fa fa-phone"></i> {{object.contact_no}}
														</li>
													</ul>
												</div>
												<div class="booking-info">
													<h2>
													<a href="{{object.get_absolute_url}}">
													{{object.name}}</a>
													</h2>
													{% if not object.blocked %}
														{% if object.verification_status %}
															<span class="label label-success">Verified</span>
														{% else %}
															<span class="label label-warning">Pending</span>
														{% endif %}
													{% else %}
														<span class="label label-danger">Blocked</span>
													{% endif %}
													<h4>{{object.average_rating}} <small><span class="fa fa-star"></span></small></h4>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			{% endfor %}
			<div class="row">
				<div class="col-md-10 col-md-offset-1">
					<div class="margin-top-20">
						<ul class="pagination pagination-square">
					        {% if object_list.has_previous %}
					        <li>
					            <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"><span aria-hidden="true">&laquo;</span></a>
					        </li>
					        {% else %}
					        	<li>
					            	<a href="#"><span aria-hidden="true">&laquo;</span></a>
					            </li>
					        {% endif %}
					        {% for i in object_list.paginator.page_range %}
					       		<li {% if i == object_list.number %}class="active"{% endif %}>
					       			<a href="?{{ page_request_var }}={{i}}">{{i}}</a>
					       		</li>
					        {% endfor %}
					        {% if object_list.has_next %}
					        <li>
					            <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"><span aria-hidden="true">&raquo;</span></a>
					          </li>
					        {% else %}
					        	<li>
					            	<a href="#"><span aria-hidden="true">&raquo;</span></a>
					            </li>
					        {% endif %}


						</ul>


					</div>

				</div>


			</div>

		</div>
	</div>
	<!-- END PAGE CONTENT -->
</div>

</section>




{% endblock content %}

templates/volunteer/report.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
	Report | {{volunteer.name}}
{% endblock  %}


{% block content %}
<div class="page-container">
	<div class="page-content">
	<div class="container">
	</div>
	</div>
	<div class="page-container">
		<div class="page-content">
			<div class="container">
			<!-- BEGIN PAGE CONTENT INNER -->
				<div class="portlet light">
					<div class="portlet-body">
						<div class="post-comment">
							<h3>Report</h3>
								<form role="form" action="" method="POST">
									{% csrf_token %}
									<div class="form-group">
										<label id="title" for="{{form.title.id_for_label}}" >Title</label>
										{{form.title}}
									</div>
									<div class="form-group">
										<label id="content" for="{{form.content.id_for_label}}" >Content</label>
										{{form.content}}
									</div>
									<button class="margin-top-20 btn blue" type="submit">Report</button>
								</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>


{% endblock content %}

templates/volunteer/report_detail.html
{% extends "base.html" %}

{% block title %}
	Report | {{report.volunteer.name}}
{% endblock  %}


{% block content %}
<div class="page-container">
	<div class="page-content">
		<div class="container">
			<div class="portlet light">
				<div class="portlet-body">
					<div class="portlet light">
						<div class="portlet-title">
							<div class="caption">
								<span style="font-size:40px;" class="caption-subject">{{report.title}}</span>
								{% if report.verification_status %}
									<span class="label label-success">Verified</span>
								{% else %}
									<span class="label label-warning">Pending</span>
								{% endif %}
							</div>
							<div class="actions">
								<a href="{% url 'verify_report' report.id %}" class="btn btn-circle btn-default">
								<i class="fa fa-edit"></i> Verify </a>
								<a href="{% url 'delete_report' report.id %}" class="btn btn-circle btn-default">
								<i class="fa fa-trash"></i> Delete</a>
							</div>
						</div>
						<div class="portlet-body">
							<h4><small><span class="fa fa-user"></span></small> <a href="{% url 'user:show_profile' report.user|slugify %}">{{report.user}}</a></h4>
							<h4><small><span class="fa fa-building"></span></small> <a href="{% url 'volunteer:show_volunteer' report.volunteer.slug %}">{{report.volunteer}}</a></h4>
							<h4><small><span class="fa fa-calendar"></span></small> {{report.timestamp}}</h4>
							<hr/>
							{{report.content}}
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock content %}