FillmeUp/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
#from posts import views

urlpatterns = [
    # Examples:

    url(r'^$', 'posts.views.home', name='home'),
    url(r'^about_us/', 'posts.views.about_us',name='about_us'),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^posts/',include("posts.urls",namespace='posts')),
    url(r'^volunteer/', include('volunteer.urls', namespace="volunteer")),
    url(r'^donate/', include('donate.urls', namespace="donate")),

    url(r'^accounts/', include('allauth.urls')),
    url(r'^account/', include('accounts.urls', namespace="accounts")),
    url(r'^user/', include('users.urls', namespace="user")),


    #url(r'^posts/$', "<appname>.views.<function_name>"),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.conf.urls import url
from . import views



urlpatterns = [

	url(r'^register/$', views.RegisterView.as_view(), name="register"),
	url(r'^login/$', views.LoginView.as_view(), name="login"),
	url(r'^logout/$', views.LogoutView.as_view(), name="logout"),
]

posts/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from .views import(
    post_list,
    post_create,
    post_delete,
    post_update,
    post_detail,
    )
#from posts import views

urlpatterns = [
    # Examples:
    #url(r'^$', '.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),


    #url(r'^$', "posts.views.post_home"),




    url(r'^$', post_list, name='list'),
    url(r'^create/$', post_create, name='create'),
    url(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', post_update, name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', post_delete),
    #url(r'^posts/$', "<appname>.views.<function_name>"),


]

accounts/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.models import User


class RegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={
		                'class': 'form-control border-square',
		                'required': 'true',
		                'placeholder': 'Password',
	            	}
            	)
    		)

    class Meta:
        model = User
        fields = [
            "username",
            "first_name",
            "last_name",
            "email",
            "password",
        ]
        widgets = {
            "first_name": forms.TextInput(attrs={
                'class': 'form-control border-square',
                'required': 'true',
                'placeholder': 'First Name',
            	}
                # label='F'
            ),
            "last_name": forms.TextInput(attrs={
                'class': 'form-control border-square',
                'required': 'true',
                'placeholder': 'Last Name',
            	}
                # label='F'
            ),
            "username": forms.TextInput(attrs={
                'class': 'form-control border-square',
                'required': 'true',
                'placeholder': 'Username',
            	}
            ),
            "email": forms.TextInput(attrs={
                'class': 'form-control border-square',
                'required': 'true',
                'placeholder': 'example@example.com',
            	}
            ),
        }


class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={
	                'class': 'form-control border-square',
	                'required': 'true',
	                'placeholder': 'Username',
            		}
            	)
    		)
    password = forms.CharField(widget=forms.PasswordInput(attrs={
		                'class': 'form-control border-square',
		                'required': 'true',
		                'placeholder': 'Password',
	            	}
	            )
    		)

    class Meta:
        fields = [
            "username",
            "password",
        ]

accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.http import Http404
from django.shortcuts import render, redirect
from django.views.generic import View
from .forms import RegistrationForm, LoginForm
from django.contrib import messages

# Create your views here.

class RegisterView(View):
    def get(self, request):
        form = RegistrationForm(request.POST or None)
        context = {
            "form":form,
            "title":"Register"
        }

        return render(request, 'accounts/register.html', context)

    def post(self,request):
        form = RegistrationForm(request.POST or None)
        if form.is_valid():
            user = form.save(commit=False)
            password = user.password
            user.set_password(password)
            user.save()

            user = authenticate(username=user.username, password=password)
            login(request, user)
            messages.success(request,"Succesfully Registered")
            return redirect('user:update_profile',user.username)
        context={
            "form":form,
            "title":"Register"
        }
        return render(request, 'accounts/register.html', context)


class LoginView(View):
    def get(self, request):
        form = LoginForm(request.POST or None)
        context = {
            "form":form,
            "title":"Login"
        }
        return render(request, 'accounts/login.html', context)

    def post(self, request):
        form = LoginForm(request.POST or None)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user and user.is_active:
                login(request,user)
                messages.success(request,"Logged In Succesfully")
                return redirect('home')

        messages.warning(request,"Invalid Username/Password")
        context = {
            "form":form,
            "title":"Login"
        }
        return render(request, "accounts/login.html", context)

class LogoutView(View):
    def get(self,request):
        logout(request)
        messages.success(request,"Logged Out Succesfully")
        return redirect('home')

templates/accounts/login.html
{% extends "base.html" %}

{% block title %}
    Login
{% endblock  %}


{% block content %}
<section class="page-banner-section">
	<div class="container">
		<h1>Sign in</h1>
	</div>
</section>
<div class="row">
  <section class="page-banner-section">
  	<div class="container">


    <div class="col-md-4 col-md-offset-4">
        <div class="portlet light">
            <div class="portlet-title">

            </div>
            <div class="portlet-body form">
                <form role="form" method="POST" action="" enctype="multipart.form-data">
                    {% csrf_token %}
                    <div class="form-body">
                        <div class="form-group">
                            <label id="username" for="{{form.username.id_for_label}}" ></label>
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <i class="fa fa-envelope"></i>
                                </span>
                                {{form.username}}
                            </div>
                        </div>
                        <div class="form-group">
                            <label id="password" for="{{form.password.id_for_label}}" ></label>
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <i class="fa fa-asterisk"></i>
                                </span>
                                {{form.password}}
                            </div>
                        </div>
                        
                        <label class="rememberme check">
                        <input type="checkbox" name="remember" value="1"/>  Remember </label>
                        <a href="javascript:;" id="forget-password" class="forget-password">Forgot Password?</a><br><br>
                        <button class="btn btn-lg btn-primary btn-block blue" type="submit">Sign in</button>
                    </div>
                </form>
                <br>Registered?? If Not, <a href="{% url 'accounts:register' %}">Register</a>
              </div>
        </div>

    </div>
</div>
</div>
</section>
<section class="page-banner-section">
	<div class="container">
		<h1>  </h1>
	</div>
</section>

{% endblock content %}

templates/accounts/register.html
{% extends "base.html" %}

{% block title %}
  Register
{% endblock  %}


{% block content %}
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="portlet light">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-pencil font-green-sharp"></i>
                        <span class="caption-subject font-green-sharp bold uppercase">Register</span>
                    </div>
                </div>
                <div class="portlet-body form">
                <form role="form" method="POST" action="" enctype="multipart.form-data">
                    {% csrf_token %}
                    <div class="form-body">
                        <div class="form-group">
                            <label id="first_name" for="{{form.first_name.id_for_label}}" >First Name</label>
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <i class="fa fa-user"></i>
                                </span>
                                {{form.first_name}}
                            </div>
                        </div>
                        <div class="form-group">
                            <label id="last_name" for="{{form.last_name.id_for_label}}" >Last Name</label>
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <i class="fa fa-user"></i>
                                </span>
                                {{form.last_name}}
                            </div>
                        </div>
                        <div class="form-group">
                            <label id="email" for="{{form.email.id_for_label}}" >Username</label>
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <i class="fa fa-envelope"></i>
                                </span>
                                {{form.email}}
                            </div>
                        </div>
                        <div class="form-group">
                            <label id="username" for="{{form.username.id_for_label}}" >Username</label>
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <i class="fa fa-user"></i>
                                </span>
                                {{form.username}}
                            </div>
                        </div>
                        <div class="form-group">
                            <label id="password" for="{{form.password.id_for_label}}" >Password</label>
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <i class="fa fa-asterisk"></i>
                                </span>
                                {{form.password}}
                            </div>
                        </div>
                        <button class="btn btn-lg btn-primary btn-block blue" type="submit">Register</button>
                    </div>
                </form>
                Already Registered?? If Yes, <a href="{% url 'accounts:login' %}">Login</a>
                </div>
              
            </div>

        </div>
    </div>
{% endblock content %}