FillmeUp/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
#from posts import views

urlpatterns = [
    # Examples:

    url(r'^$', 'posts.views.home', name='home'),
    url(r'^about_us/', 'posts.views.about_us',name='about_us'),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^posts/',include("posts.urls",namespace='posts')),
    url(r'^volunteer/', include('volunteer.urls', namespace="volunteer")),
    url(r'^donate/', include('donate.urls', namespace="donate")),

    url(r'^accounts/', include('allauth.urls')),
    url(r'^account/', include('accounts.urls', namespace="accounts")),
    url(r'^user/', include('users.urls', namespace="user")),


    #url(r'^posts/$', "<appname>.views.<function_name>"),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.conf.urls import url
from . import views



urlpatterns = [

	url(r'^register/$', views.RegisterView.as_view(), name="register"),
	url(r'^login/$', views.LoginView.as_view(), name="login"),
	url(r'^logout/$', views.LogoutView.as_view(), name="logout"),
]

posts/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from .views import(
    post_list,
    post_create,
    post_delete,
    post_update,
    post_detail,
    )
#from posts import views

urlpatterns = [
    # Examples:
    #url(r'^$', '.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),


    #url(r'^$', "posts.views.post_home"),




    url(r'^$', post_list, name='list'),
    url(r'^create/$', post_create, name='create'),
    url(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', post_update, name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', post_delete),
    #url(r'^posts/$', "<appname>.views.<function_name>"),


]

users/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
	url(r'^list/', ListView.as_view(), name="list_user"),
	url(r'^(?P<slug>[\w-]+)/$', ProfileView.as_view(), name="show_profile"),
	url(r'^(?P<slug>[\w-]+)/update/$', UpdateView.as_view(), name="update_profile"),
	url(r'^(?P<slug>[\w-]+)/delete/$', DeleteView.as_view(), name="delete_profile"),
	url(r'^(?P<slug>[\w-]+)/block/$', BlockView.as_view(), name="block_profile"),
]

volunteer/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [
	url(r'^list/$', ListView.as_view(), name="list_volunteer"),
	url(r'^add/$', CreateView.as_view(), name="add_volunteer"),
	url(r'^(?P<slug>[\w-]+)/$', DetailView.as_view(), name="show_volunteer"),
	url(r'^(?P<slug>[\w-]+)/update/$', UpdateView.as_view(), name="update_volunteer"),
	url(r'^(?P<slug>[\w-]+)/delete/$', DeleteView.as_view(), name="delete_volunteer"),
	url(r'^(?P<slug>[\w-]+)/block/$', BlockView.as_view(), name="block_volunteer"),
	url(r'^(?P<slug>[\w-]+)/report/$', ReportView.as_view(), name="report_volunteer"),
]

posts/models.py
from __future__ import unicode_literals
from django.core.urlresolvers import reverse
from django.db.models.signals import pre_save
from django.db import models
from django.utils.text import slugify
from django.conf import settings
from django.utils import timezone

# Create your models here.
class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        return super(PostManager,self).filter(draft=False).filter(publish__lte=timezone.now())

def upload_location(instance, filename):
    # filebase,extension=filename.splot(".")
    # return "%s/%s.%s"%(instance.id,filename,extension)

    return "%s/%s"%(instance.id,filename)



class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,default=1)
    title = models.CharField(max_length=120)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to=upload_location,
    null=True, blank=True,width_field="width_field",height_field="height_field")
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    draft=models.BooleanField(default=False)
    publish=models.DateField(auto_now=False,auto_now_add=False)
    content = models.TextField()
    updated = models.DateTimeField(auto_now=True,auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False,auto_now_add=True)

    objects=PostManager()

    def __uncode__(self):
        return self.title

    def __str__(self):
        return self.title

    def get_absoulute_url(self):
        return reverse("posts:detail", kwargs={"slug": self.slug})

    class Meta:
        ordering = ["-timestamp","-updated"]
def create_slug(instance,new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug=new_slug
    qs=Post.objects.filter(slug=slug).order_by("-id")
    exists=qs.exists()
    if exists:
        new_slug="%s-%s"%(slug,qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug

def pre_save_post_receiver(sender,instance,*args,**kwargs):
    if not instance.slug:
        instance.slug=create_slug(instance)

pre_save.connect(pre_save_post_receiver,sender=Post)

posts/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            "title",
            "content",
            "image",
            "draft",
            "publish",
        ]

posts/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.http import HttpResponse, HttpResponseRedirect,Http404
from .models import Post
from .forms import PostForm
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from urllib import quote_plus
from django.utils import timezone
from django.db.models import Q



def post_create(request):
    if not request.user.is_active:
        if not request.user.is_staff or not request.user.is_superuser:
            raise Http404

    form = PostForm(request.POST or None,request.FILES or None)
    if form.is_valid():
        instance= form.save(commit = False)
        instance.user = request.user
        instance.save()
        messages.success(request, "Succesfully Created")
        return HttpResponseRedirect(instance.get_absoulute_url())
    context = {
        "form" : form,

    }
    return render(request,"post_form.html",context)

def post_detail(request,slug):
    #instance= Post.objects.get(slug=1)
    instance = get_object_or_404(Post, slug=slug)
    if instance.publish > timezone.now().date() or instance.draft:
        if not request.user.is_staff or not request.user.is_superuser:
            raise Http404
    share_string = quote_plus(instance.content)
    context = {
        "title": instance.title,
        "instance" : instance,
        "share_string":share_string,
    }
    return render(request,"post_detail.html",context)
    #return HttpResponse("<h1>detail</h1>")

def post_list(request):
	today = timezone.now().date()
	queryset_list = Post.objects.active() #.order_by("-timestamp")
	if request.user.is_staff or request.user.is_superuser:
		queryset_list = Post.objects.all()

	query = request.GET.get("q")
	if query:
		queryset_list = queryset_list.filter(
				Q(title__icontains=query)|
				Q(content__icontains=query)|
				Q(user__first_name__icontains=query) |
				Q(user__last_name__icontains=query)
				).distinct()
	paginator = Paginator(queryset_list, 8) # Show 25 contacts per page
	page_request_var = "page"
	page = request.GET.get(page_request_var)
	try:
		queryset = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		queryset = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		queryset = paginator.page(paginator.num_pages)


	context = {
		"object_list": queryset,
		"title": "List",
		"page_request_var": page_request_var,
		"today": today,
	}
	return render(request, "post_list.html", context)


def post_update(request,slug=None):
    if not request.user.is_staff or not request.user.is_superuser:
        return Http404
    instance = get_object_or_404(Post, slug=slug)
    form = PostForm(request.POST or None,request.FILES or None, instance=instance)
    if form.is_valid():
        instance= form.save(commit = False)
        instance.save()
        messages.success(request, "<a href='#'> Item </a>Saved",extra_tags='html_safe')
        return HttpResponseRedirect(instance.get_absoulute_url())

    context = {
        "title": instance.title,
        "instance" : instance,
        "form" : form,
    }
    return render(request,"post_form.html",context)



def post_delete(request,slug=None):
    if request.user.is_staff or not request.user.is_superuser:
        return Http404
    instance = get_object_or_404(Post, slug=slug)
    instance.delete()
    messages.success(request, "Succesfully Deleted")
    return redirect("posts:list")
def home(request,slug=None):

    return render(request,"home.html")
def about_us(request,slug=None):
    return render(request,"about_us.html",{})
# Create your views here.

templates/base.html
<!doctype html>
{%load staticfiles%}
<html lang="en" class="no-js" xml:lang="nep">
<head>
	<title>{%block title_head%}Fill-me Up | Donation Website{%endblock title_head%}</title>

	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">



	<link href='http://fonts.googleapis.com/css?family=Montserrat:300,400,700' rel='stylesheet' type='text/css'>
	<link href='https://fonts.googleapis.com/css?family=Raleway:400,300,500,600,700' rel='stylesheet' type='text/css'>
	<link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,400italic' rel='stylesheet' type='text/css'>


	<link rel="stylesheet" type="text/css" href='{%static "css/bootstrap.min.css"%}' media="screen">
	<link rel="stylesheet" type="text/css" href='{%static "css/jquery.bxslider.css"%}' media="screen">
	<link rel="stylesheet" type="text/css" href='{%static "css/owl.carousel.css"%}' media="screen">
  <link rel="stylesheet" type="text/css" href='{%static "css/owl.theme.css"%}' media="screen">
	<link rel="stylesheet" type="text/css" href='{%static "css/font-awesome.css"%}' media="screen">

	<!-- REVOLUTION STYLE SHEETS -->
	<link rel="stylesheet" type="text/css" href='{%static "css/settings.css"%}'>
	<!-- REVOLUTION LAYERS STYLES -->
	<link rel="stylesheet" type="text/css" href='{%static "css/layers.css"%}'>
	<!-- REVOLUTION NAVIGATION STYLES -->
	<link rel="stylesheet" type="text/css" href='{%static "css/navigation.css"%}'>

	<link rel="stylesheet" type="text/css" href='{%static "css/style.css" %}' media="screen">


	<script type="text/javascript" src='{%static "js/jquery.min.js"%}'></script>
	<script type="text/javascript" src='{%static "js/jquery.migrate.js"%}'></script>
	<script type="text/javascript" src='{%static "js/jquery.bxslider.min.js"%}'></script>
	<script type="text/javascript" src='{%static "js/jquery.appear.js"%}'></script>
	<script type="text/javascript" src='{%static "js/jquery.countTo.js"%}'></script>
	<script type="text/javascript" src='{%static "js/owl.carousel.min.js"%}'></script>
	<script type="text/javascript" src='{%static "js/bootstrap.min.js"%}'></script>
	<script type="text/javascript" src='{%static "js/jquery.imagesloaded.min.js"%}'></script>
	<script type="text/javascript" src='{%static "js/retina-1.1.0.min.js"%}'></script>

	<!-- REVOLUTION JS FILES -->
	<script type="text/javascript" src='{%static "js/jquery.themepunch.tools.min.js"%}'></script>
	<script type="text/javascript" src='{%static "js/jquery.themepunch.revolution.min.js"%}'></script>

	<!-- SLIDER REVOLUTION 5.0 EXTENSIONS
		(Load Extensions only on Local File Systems !
		The following part can be removed on Server for On Demand Loading) -->
	<script type="text/javascript" src='{%static "js/extensions/revolution.extension.actions.min.js"%}'></script>
	<script type="text/javascript" src='{%static "js/extensions/revolution.extension.carousel.min.js"%}'></script>
	<script type="text/javascript" src='{%static "js/extensions/revolution.extension.kenburn.min.js"%}'></script>
	<script type="text/javascript" src='{%static "js/extensions/revolution.extension.layeranimation.min.js"%}'></script>
	<script type="text/javascript" src='{%static "js/extensions/revolution.extension.migration.min.js"%}'></script>
	<script type="text/javascript" src='{%static "js/extensions/revolution.extension.navigation.min.js"%}'></script>
	<script type="text/javascript" src='{%static "js/extensions/revolution.extension.parallax.min.js"%}'></script>
	<script type="text/javascript" src='{%static "js/extensions/revolution.extension.slideanims.min.js"%}'></script>
	<script type="text/javascript" src='{%static "js/extensions/revolution.extension.video.min.js"%}'></script>

	<script type="text/javascript" src='{%static "js/script.js"%}'></script>


</head>



</style>
</head>
<body>

	<!-- Container -->
	<div id="container">
		<!-- Header
		    ================================================== -->
				<header>
				<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
						<div class="top-line">
							<div class="container">
								<div class="row">
									<div class="col-md-8">
										<ul class="info-list">
									<li>
										<i class="fa fa-globe"></i>
										Language: <span title="English"><a lang="en" href="#">English</a></span>
									</li>
									<li>
										<i class="fa fa-phone"></i>
										Call us:
										<span>+977 9843002632</span>
									</li>

								</ul>
									</div>
									<div class="col-md-4">
										<ul class="social-icons">
											<li><a class="facebook" href="#"><i class="fa fa-facebook"></i> | </a></li>
											<li><a class="twitter" href="#"><i class="fa fa-twitter"></i> | </a></li>
											<li><a class="google" href="#"><i class="fa fa-google-plus"></i> | </a></li>
											<li><a class="linkedin" href="#"><i class="fa fa-linkedin"></i> | </a></li>
											<li><a class="dribble" href="#"><i class="fa fa-dribbble"></i> | </a></li>
										</ul>
									</div>
								</div>
							</div>
						</div>
						<div class="container">
							<!-- Brand and toggle get grouped for better mobile display -->

							<!-- Collect the nav links, forms, and other content for toggling -->
							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
								<ul class="nav navbar-nav navbar-right">
									<li><a class="active" href="{% url 'home' %}">Home</a></li>
									<li><a href="{% url 'donate:list' %}">Donations</a></li>
									<li><a href="{%url 'volunteer:list_volunteer'%}">Events</a></li>
									<li><a href="{% url 'user:list_user' %}">User List</a></li>
									<li><a href="{% url 'posts:list' %}">Blogs</a></li>
									<li>{% if request.user.is_active%}
                                <img alt="" class="img-circle" src="{% static 'default.png' %}">
                                {% endif %}

                                    {% if request.user.is_active %}
                                      {% if request.user.is_superuser %}
                                      <a href="/admin/">Admin</a>
                                      {% else %}
                                      <a href='{% url "accounts:logout" %}'>{{request.user.get_full_name}} | Logout</a>
                                      {% endif %}
                                    {% else %}
                                    <a href='{% url "accounts:login" %}'>Sign In / Up</a>
                                    {% endif %}</a></li>
									<li class="search"><a href="#" class="open-search"><i class="fa fa-search"></i></a>
								<form class="form-search" method='GET' action=''>
									<input type="search" placeholder="Search:"/>
									<button type="submit">
										<i class="fa fa-search"></i>
									</button>
								</form>
							</li>
								</ul>
							</div><!-- /.navbar-collapse -->
						</div><!-- /.container-fluid -->
					</nav>
				</header>
		<!-- End Header -->
{%block content%}
{%endblock content%}

		<!-- subcribe-section
			================================================== -->
		<section class="subcribe-section">
			<div class="container">
				<div class="title-section white">
					<h1>Join Us</h1>
				</div>
					<form class="subscribe">

					<a href="#" class="button-one"><h4>SignUp</h4></a>
				</form>
				<p>Please contact us if you want to do charity through the mailbox.</p>
			</div>
		</section>
		<!-- End subscribe section -->

		<!-- footer
			================================================== -->
		<footer>
			<div class="container">
				<div class="row">
					<div class="col-md-4">
						<div class="contact-info">
							<h2><i class="fa fa-location-arrow"></i> Our Address</h2>
							<p>Fill-me Up</br>Pukchowk, Lalitpur, Nepal.</p>
						</div>
					</div>
					<div class="col-md-4">
						<div class="contact-info">
							<h2><i class="fa fa-envelope-o"></i> Contact Us</h2>
							<p>+977 9843002632 </p>
						</div>
					</div>
					<div class="col-md-4">
						<div class="contact-info">
							<h2><i class="fa fa-clock-o"></i> Office hours</h2>
							<p>Monday to Friday: 10:00 - 17:00 <br> Saturday, Sunday: 10:00 - 13:00</p>
						</div>
					</div>
				</div>
			</div>
		</footer>
		<!-- End footer -->

	</div>
	<!-- End Container -->

	<!-- Revolution slider -->
	<script type="text/javascript">
		var tpj=jQuery;
		var revapi66;
		tpj(document).ready(function() {
			if(tpj("#rev_slider_66_1").revolution == undefined){
				revslider_showDoubleJqueryError("#rev_slider_66_1");
			}else{
				revapi66 = tpj("#rev_slider_66_1").show().revolution({
					sliderType:"standard",
					jsFileLocation:"js/",
					sliderLayout:"fullwidth",
					dottedOverlay:"none",
					gridheight:600,
					gridwidth:1140,
					delay:9000,
					navigation: {
						keyboardNavigation:"off",
						keyboard_direction: "horizontal",
						mouseScrollNavigation:"off",
						onHoverStop:"off",
						touch:{
							touchenabled:"on",
							swipe_threshold: 75,
							swipe_min_touches: 1,
							swipe_direction: "vertical",
							drag_block_vertical: false
						},
                        arrows: {
                            style: "uranus",
                            enable: true,
                            hide_onmobile: true,
                            hide_under: 778,
                            hide_onleave: true,
                            hide_delay: 200,
                            hide_delay_mobile: 1200,
                            tmp: '',
                            left: {
                                h_align: "left",
                                v_align: "center",
                                h_offset: 20,
                                v_offset: 0
                            },
                            right: {
                                h_align: "right",
                                v_align: "center",
                                h_offset: 20,
                                v_offset: 0
                            }
                        }
					},
					lazyType:"none",
					shadow:0,
					spinner:"off",
					stopLoop:"on",
					stopAfterLoops:0,
					stopAtSlide:1,
					shuffle:"off",
					autoHeight:"off",
					fullScreenAlignForce:"off",
					fullScreenOffsetContainer: "",
					fullScreenOffset: "",
					disableProgressBar:"on",
					hideThumbsOnMobile:"off",
					hideSliderAtLimit:0,
					hideCaptionAtLimit:0,
					hideAllCaptionAtLilmit:0,
					debugMode:false,
					fallbacks: {
						simplifyAll:"off",
						nextSlideOnWindowFocus:"off",
						disableFocusListener:false,
					}
				});
			}
		});	/*ready*/
	</script>
</body>
</html>

templates/messages_display.html
{%if messages %}
<div class='messages'>
<ul class="messages">
{% for message in messages %}
<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{% if "html_safe" in message.tags %}{{message|safe}}{% else %}{{ message }}{% endif %}</li>
{% endfor %}
</ul>
</div>
{% endif %}

templates/post_detail.html
{%extends "base.html"%}


{%block head_title  %}
{{instance.title}} | {{block.super}}
{% endblock head_title %}
{%block content%}

<div class="container">
<div class='col-sm-6 col-sm-offset-3'>
{%if instance.image%}
  <img src='{{instance.image.url}}' class='img-responsive'/>
{%endif%}
<h1>{{ title }}<small> {%if instance.draft%}<span style='color:red;'>Draft</span>{%endif%}{{instance.publish}} </small></h1>
{% if instance.user.get_full_name %}
<p>Author: {{instance.user.get_full_name}} </p>
{%endif%}
<p><div class="fb-like" data-href="{{request.build_absulute_url}}" data-layout="button_count" data-action="like" data-size="small" data-show-faces="false" data-share="true"></div>

</p>
<hr>
<div class='row'>
<div class='col-sm-12'>
{{instance.content | linebreaks}}
<hr/>
<br/>
<div class="fb-comments" data-href="{{request.build_absulute_url}}" data-numposts="5"></div>

</div>
</div>
</div>
</div>
{%endblock content%}

templates/post_form.html
{%  extends "base.html" %}
{%block title_head%}Blogs | Add New {%endblock title_head%}
{% block content %}
<div class='container'>
  <div class='col-sm-6 col-sm-offset-3'>
    <h1>Add Content</h1>

    <form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
      {{ form.as_p }}
      <input type= 'submit' class='btn btn-default' value='Create Post' />

    </form>
  </div>

</div>
{% endblock content %}

templates/post_list.html
{% extends "base.html" %}
{% block content %}
<div class='container'>
		<!-- page-banner-section
			================================================== -->
		<section class="page-banner-section">
			<div class="container">
				<h1>Our Blog</h1>
			</div>
		</section>
		<!-- End page-banner section


              			================================================== -->
              		<section class="blog-section">
              			<div class="container">
              				<div class="row">
              					<div class="col-md-8">
              						<div class="blog-box">

              							<div class="blog-post">
                              {% for obj in object_list %}
                              {% if obj.image %}
                              <img src='{{obj.image.url}}' class='img-responsive'/>
                              {%endif%}
              								<div class="post-content-text">
                                <h3><a href='{{ obj.get_absoulute_url }}'>{{obj.title}} </a><small>{{obj.publish}}</small></br>
                        </h3>   {% if obj.user.get_full_name %}<p>Author: {{ obj.user.get_full_name}}</p>{%endif%}
                                <p>{{obj.content|linebreaks|truncatechars:120}}</br>
              									<a href="{{ obj.get_absoulute_url }}">Read More <i class="fa fa-angle-right"></i></a>
              								</div>
                              {%endfor%}
              							</div>



              							<ul class="pagination-list">
              								<li><a href="#" class="prev-pag">prev</a></li>
              								<li><a href="#" class="active">1</a></li>
              								<li><a href="#">2</a></li>
              								<li><a href="#">3</a></li>
              								<li><a href="#" class="next-pag">next</a></li>
              							</ul>


              						</div>
													<a href="{%url 'posts:create'%}" class="button-one">
													<input type='submit' value='   Add   '>

												</input>

              					</div>
              					<div class="col-md-4">
              						<div class="sidebar">

              							<div class="category-widget widget">
              								<h2>Categories</h2>
              								<ul class="category-list">
              									<li><a href="#">Donation</span></a></li>
              									<li><a href="#">Volunteer</span></a></li>
              									<li><a href="#">Help & Support</span></a></li>
              								</ul>
              							</div>


              							<div class="archieve-widget widget">
              								<h2>archieve</h2>
              								<ul class="archieve-list">
              									<li><a href="#">September 2014</a></li>
              									<li><a href="#">Octomber 2014</a></li>
              									<li><a href="#">November 2014</a></li>
              									<li><a href="#">December 2014</a></li>
              									<li><a href="#">Jannuary 2015</a></li>
              								</ul>
              							</div>

              							<div class="tags-widget widget">
              								<h2>TAG Widget</h2>
              								<ul class="tags-list">
              									<li><a href="#">Membership</a></li>
              									<li><a href="#">Volunteering</a></li>
              									<li><a href="#">Donating</a></li>
              									<li><a href="#">Helping Victims</a></li>
              								</ul>
              							</div>

              						</div>
              					</div>
              				</div>
              			</div>
              		</section>
              		<!-- End blog section -->







{% endblock content %}